### ISSUE TITLE
Crash on launching

### ISSUE THREAD

**Issue by carmelo-ruota** [lipangit/TestExoPlayer#1]
`FATAL EXCEPTION: main
                                                   Process: com.bitebidaquan.bitdata.testexoplayer, PID: 28393
                                                   java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.bitebidaquan.bitdata.testexoplayer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.bitebidaquan.bitdata.testexoplayer-1, /system/lib]]
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.bitebidaquan.bitdata.testexoplayer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.bitebidaquan.bitdata.testexoplayer-1, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515)`

**Comment by lipangit** [comment]
This project can not use, It just for test fullscreen.
